
@Component
struct BottomInput {
  @State showVoice:boolean = false
  build() {
    Column(){
      Row({space: 10}){
        Image(this.showVoice?$r("app.media.ic_public_keyboard"):$r("app.media.ic_public_sound"))
          .width(25)
          .height(25)
          .onClick(() => {
            this.showVoice =! this.showVoice
          })

        if(this.showVoice){
          Button("按住 说话",{
            type: ButtonType.Normal
          })
            .backgroundColor(Color.White)
            .height(35)
            .layoutWeight(1)
            .borderRadius(2)
            .fontColor($r("app.color.text_primary"))
        }else{
          TextInput()
            .layoutWeight(1)
            .height(35)
            .borderRadius(2)
            .backgroundColor(Color.White)
        }
        Image($r("app.media.ic_public_add_norm"))
          .width(25)
          .height(25)
      }
      .width("100%")
      .height(60)
      .padding({
        left:10,
        right:10
      })

    }
    .backgroundColor($r("app.color.second_back_color"))

  }
}

export default BottomInput
