export interface UserInfo{
  user_id: string
  avatar:string
  username:string
}

export const DefaultUserList:UserInfo[] = [
  {
    user_id: "1",
    username: "aaaa",
    avatar:"app.media.tx"
  },
  {
    user_id: "2",
    username: "bbb",
    avatar:"app.media.tx"
  },
  {
    user_id: "3",
    username: "ccc",
    avatar:"app.media.tx"
  },
  {
    user_id: "4",
    username: "ddd",
    avatar:"app.media.tx"
  },
  {
    user_id: "5",
    username: "eee",
    avatar:"app.media.tx"
  },
  {
    user_id: "6",
    username: "fff",
    avatar:"app.media.tx"
  },
  {
    user_id: "7",
    username: "ggg",
    avatar:"app.media.tx"
  },
  {
    user_id: "8",
    username: "hhh",
    avatar:"app.media.tx"
  }
]